### ISSUE TITLE
Spanner reduction in kharita_star.py

### ISSUE THREAD

**Issue by mattbrown11** [vipyoung/kharita#1]
It appears that kharita_star.py does not apply the spanner reduction in its processing. Is the intention to run the spanner reduction as a separate process?

**Comment by vipyoung** [comment]
The "online" version of the spanner was implemented as condition on whether or not  to add an edge to the graph (see commented line142.) It turned out that the graphs produced from the data we had access to were just fine without spanners.

Unlike kharita_star.py, the map quality of the offline algorithm in kharita.py heavily depends on the use of graph spanners.

**Comment by mattbrown11** [comment]
Thanks!
